### ISSUE TITLE
window10 go build not success

### ISSUE THREAD

**Issue by taozywu** [mfbonfigli/gocesiumtiler#10]
1. gcc-64: mingw64（64）、branch: decoupling_tree_data_structure
2. go mod tidy 
3. go mod vendor
4. go build, it will have some problems and not succeed. as follow:

```
PS D:\Work\GoWork\gocesiumtiler> go build                                                                               # runtime
textflag.h:1: '#' must be first item on line
# runtime/cgo
gcc_freebsd_sigaction.c:19:25: error: '_SIG_WORDS' undeclared here (not in a function); did you mean 'SIG_ERR'?
         uint32_t __bits[_SIG_WORDS];
                         ^~~~~~~~~~
                         SIG_ERR
gcc_freebsd_sigaction.c: In function 'x_cgo_sigaction':
gcc_freebsd_sigaction.c:30:19: error: storage size of 'act' isn't known
  struct sigaction act;
                   ^~~
gcc_freebsd_sigaction.c:31:19: error: storage size of 'oldact' isn't known
  struct sigaction oldact;
                   ^~~~~~
gcc_freebsd_sigaction.c:40:22: error: 'SA_SIGINFO' undeclared (first use in this function); did you mean 'SIGINT'?
   if (goact->flags & SA_SIGINFO) {
                      ^~~~~~~~~~
                      SIGINT
gcc_freebsd_sigaction.c:40:22: note: each undeclared identifier is reported only once for each function it appears in
gcc_freebsd_sigaction.c:41:37: error: unknown type name 'siginfo_t'
    act.sa_sigaction = (void(*)(int, siginfo_t*, void*))(goact->handler);
                                     ^~~~~~~~~
gcc_freebsd_sigaction.c:41:56: error: expected ';' before '(' token
    act.sa_sigaction = (void(*)(int, siginfo_t*, void*))(goact->handler);
                                                        ^
                                                        ;
gcc_freebsd_sigaction.c:45:3: error: implicit declaration of function 'sigemptyset' [-Werror=implicit-function-declaration]
   sigemptyset(&act.sa_mask);
   ^~~~~~~~~~~
gcc_freebsd_sigaction.c:48:5: error: implicit declaration of function 'sigaddset' [-Werror=implicit-function-declaration]
     sigaddset(&act.sa_mask, i+1);
     ^~~~~~~~~
gcc_freebsd_sigaction.c:54:8: error: implicit declaration of function 'sigaction'; did you mean 'x_cgo_sigaction'? [-Werror=implicit-function-declaration]
  ret = sigaction(signum, goact ? &act : NULL, oldgoact ? &oldact : NULL);
        ^~~~~~~~~
        x_cgo_sigaction
gcc_freebsd_sigaction.c:71:8: error: implicit declaration of function 'sigismember' [-Werror=implicit-function-declaration]
    if (sigismember(&oldact.sa_mask, i+1) == 1) {
        ^~~~~~~~~~~
gcc_freebsd_sigaction.c:31:19: error: unused variable 'oldact' [-Werror=unused-variable]
  struct sigaction oldact;
                   ^~~~~~
gcc_freebsd_sigaction.c:30:19: error: unused variable 'act' [-Werror=unused-variable]
  struct sigaction act;
                   ^~~
cc1.exe: all warnings being treated as errors
```
Looking forward to your reply!

**Comment by taozywu** [comment]
it's ok with linux(branch: decoupling_tree_data_structure   linux: centos6.9), but it has some questions.

i use this command
```
./gocesiumtiler -i ./demo.las -o ./demo -e 32650 -m 1000000 -g -f -r -hq
```
1. the result time is over five mintues. and i try '-m 50000', It's still slow. 
2. the pnts file is still so big.
3. the las file link i want to give you, what receiver are you going to use? 
----
I'm still trying to do something else.

**Comment by mfbonfigli** [comment]
1. **Problems with pnts file size**
If you checked out the `decoupling_tree_data_structure` branch the `-m` flag will have no effect by default, it only works if you use one of the older algorithms. (Btw I just released this algorithm in new revision 1.1.0, so it is already in the master and in the windows prebuild binary)

The new algorithm can be tuned using the following flags:
- `x`: approximate distance in meters between adjacent points at the lowest level of detail (more coarse cloud). If you use `-x 20` at the lowest level of detail will have one point every 20 meters. With this you can anticipate the number of points produced in the output. The more the cloud gets bigger the higher should this parameter `x` be, otherwise you will end up having too many points in your tiles.
- `n`: minimum distance under which all points are sampled. If you have `x` = 10, every LOD will half this initial distance by two, until it gets to `n`. This means that first (lower level of detail) LOD you will have 1 point every 10 meters, then at next LOD 1 point every 5m, then 1 every 2.5m, then 1 every 1.25m and this will go on until it reaches `n`. With this you control the granularity. If you have a huge difference between `x` and `n` you will get a highly nested structure (many LODs), which could be not desireable, if the difference is too low you might end up having tiles with too many points. 

I am working on making the algorithm smart and select these automatically but for now they have to be specified manually. The defaults are `x=5` and `n=0.15` which is ok for the point cloud I am using (approximately a scan of a street 1km long with point density of 1pt every 1-2cm).

2. **Problem building under Windows**
To be honest I don't know what the issue could be, I am not an expert of building C / C++ code, but I it may be due to the fact that we are using an old Proj4 build library. Running `gcc --version` on my system returns `gcc (tdm64-1) 5.1.0` this GCC version on my machine and it builds, maybe you could try to install this TDM GCC compiler version to match my configuration and see if it works.

3. **Providing example point cloud file**
You can upload it to MEGA or dropbox (or any other file sharing service) and share the link here or send me an email to m.federico.bonfigli@gmail.com if you want it to stay private. I will try to give it a look! Also please remember to provide the EPSG code of the point cloud!

**Comment by taozywu** [comment]
@mfbonfigli 
First i can try it, second i will give you the point cloud file links to your email. of course I try them all myself, even though I don't know much about Go.I'm sorry to take up your time.

Thank you

**Comment by taozywu** [comment]
@mfbonfigli 
![image](https://user-images.githubusercontent.com/2793680/104864830-3464d080-5975-11eb-88ef-2a03638545ca.png)

I found this error when I try it, as shown in the picture above.It looks like the path is fixed by error.

Please check it. Thank you！

**Comment by taozywu** [comment]
@mfbonfigli 

I'm sorry to have taken you so long time, I found that it was caused by the encryption software installed on my computer, and my other computer could run normally without the encryption software under window. Anyway, thanks!
