### ISSUE TITLE
Support for 1.1 of the 3D Tiles Specification?

### ISSUE THREAD

**Issue by sweco-sekrsv** [mfbonfigli/gocesiumtiler#32]
Hi!

Are there plans to support 1.1 of the 3D Tiles Specification?
https://docs.ogc.org/cs/22-025r4/22-025r4.html

In short, some formats such as Batched 3D Model (b3dm),	Instanced 3D Model (i3dm), Point Cloud (pnts) and Composite (cmpt) have been deprecated. Now all formats use glTF with extensions instead.

**Comment by mfbonfigli** [comment]
Thanks for opening this issue. As of now the library is maintained on my free time as best effort, so I can't promise if and when 3D Tiles 1.1 support will come, however if there are community contributions I'll be happy to ease them into the codebase.

**Comment by mfbonfigli** [comment]
Hi, I just released v2.0.0-beta which adds experimental support for 3D Tiles 1.1 and thus generates tiles in the glTF (.glb) format. To use just add the `-v 1.1` flag to the CLI command. Please read the "known caveats" section in the README if you have issues with washed out colors after the conversion.

Since support for 3D Tiles v 1.1 has been added, I'm closing this issue. Please feel free to open a new Issue in case you identify any problem with the implementation.
