### ISSUE TITLE
Do you still updating this library? it will really help if you support Draco algorithm

### ISSUE THREAD

**Issue by danny-wang** [mfbonfigli/gocesiumtiler#37]

**Comment by mfbonfigli** [comment]
I am still taking a look at the open issues every now and then and working on it but at a very slow pace due to lack of time. Having said this, moving to the new 3d tiles format will likely the priority feature over others. Help is always welcome :)

**Comment by mfbonfigli** [comment]
I'm closing this one. With the shift to 3D Tiles 1.1 specs, Draco is not the viable compression strategy anymore for point clouds since it does not support point features in combination with the glTF format. 

Moving forward I'll rather consider implementing `EXT_meshopt_compression` and `KHR_mesh_quantization`.

**References:**
- https://github.com/KhronosGroup/glTF/issues/1809
- https://github.com/CesiumGS/3d-tiles/blob/main/specification/TileFormats/glTF/MIGRATION.adoc
>[EXT_meshopt_compression](https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Vendor/EXT_meshopt_compression) and [KHR_mesh_quantization](https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Khronos/KHR_mesh_quantization) may be used for point cloud compression. [3DTILES_draco_point_compression](https://github.com/CesiumGS/3d-tiles/tree/main/extensions/3DTILES_draco_point_compression/) is not directly supported in glTF because [KHR_draco_mesh_compression](https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Khronos/KHR_draco_mesh_compression) only supports triangle meshes.
