### ISSUE TITLE
Large PNTS files cause slow loading

### ISSUE THREAD

**Issue by taozywu** [mfbonfigli/gocesiumtiler#9]
First, thanks for providing such a powerful tool. It's great!

A few minor problems were found after the conversion, as follows:

1. Many PNT files are over 20M in size，I found Google Draco compression in my search, but I don't know how to get started. I'm not familiar with Go.
2. Path directory is too deep, can you use it like '01_01/02_02/1.pnts', so that I can understand the directory index faster?
3. Or can you offer some ideas?

I'm sorry for my poor english, Looking forward to your reply!

**Comment by mfbonfigli** [comment]
So answering to your comments:

1. First thing I would try to reduce pnts size is to reduce the maxpts setting. In any case, I am working on a much better sampling algorithm (although a bit slower) that should hopefully solve some these issues. For sure it should help with pnts file size as it creates a much more gradual and regular subdivision (more smaller files). There is a dev branch you can try to check out to try it! If you have problems trying it let me know, I'll try to help. I am planning to do a release soon (few weeks, fingers crossed).

2. For file name I didn't get the suggestion, maybe you can expand on that. For now I am not planning to change it, but in future I will try to make it customizable. Anyway if you build the code on your own it will be quite easy to adapt it to your needs.

3. I'd really like to integrate draco, but I simply don't have the knowledge required nor I have to time to develop such knowledge as of now :(

Also one of the problems I have to work on this library (set aside not having enough time) is that I don't have access (anymore) to good point clouds to use to test it, so if you  or anyone else has even just 1 good quality point clouds that could be shared here (or even privately with me) that would really be helpful, so that I can check how the algorithm works in different settings and spot more easily issues like the one of pants size you mentioned.

**Comment by taozywu** [comment]
@mfbonfigli 
Thank you very much for your reply. i'll try it for your dev branch. and if I have time, I will also try to learn GO. becaus it's a great project!

**Comment by mfbonfigli** [comment]
I will close this issue, let's continue the discussion in the other issue you created :)
